### ISSUE TITLE
side buttons don't work in macOS Mojave

### ISSUE THREAD

**Issue by derekyin** [archagon/sensible-side-buttons#27]
It appears that the app is broken in macOS Mojave.

will attach more details after some investigation.

EDIT: v1.0.6, accessibility access allowed

**Comment by archagon** [comment]
Do you have the latest version? Mojave apps have to request accessibility access, I added that in the last release.

**Comment by derekyin** [comment]
yea, I've updated the original post to reflect this

**Comment by xlanor** [comment]
Tested with macOS Mojave v1.0.6, it's working for me.

**Comment by ivancuric** [comment]
Works here as well. Also huge thanks for this project. 👍

**Comment by kevinjfoley** [comment]
Make sure you click "Enabled" in the menu.  With 1.0.5 wouldn't enable for me after installing Mojave.  After installing 1.0.6 the side buttons still weren't working until I enabled it.

**Comment by derekyin** [comment]
> Make sure you click "Enabled" in the menu. With 1.0.5 wouldn't enable for me after installing Mojave. After installing 1.0.6 the side buttons still weren't working until I enabled it.

wow, can't believe I missed this, solved!

**Comment by Prototyped** [comment]
Having to enable Sensible Side Buttons from the menu bar icon caught me out as well. I'd consider this a usability or at least a discoverability problem. In my case, since I keep my menu bar hidden until I need to use it, it wasn't even in my field of view.

Perhaps one way around it is to prompt to enable it during the first run, and pointing out that it can be enabled or disabled from the menu bar icon?
