### ISSUE TITLE
Vivaldi support?

### ISSUE THREAD

**Issue by revunix** [archagon/sensible-side-buttons#32]
Hey,

The Vivaldi Browser is currently not supported. Can this still be made up?

Greetings,
alex

**Comment by Zegnat** [comment]
I think this is a feature request to take to Vivaldi. The side buttons are mapped to three-finger swipes, meaning that Vivaldi does not support a popular macOS interaction.

A quick search on the Vivaldi forum tells me they have never supported either [two -finger](https://forum.vivaldi.net/topic/2064/two-finger-swipe-to-navigate-back-forwards) or [three-finger swipes](https://forum.vivaldi.net/topic/9800/three-finger-swipe), so I am unsure if this is much of a priority to them. (Those topics are old, but from your issue here I am assuming they haven’t been fixed :wink:)

**Comment by revunix** [comment]
@Zegnat It was a mistake on Vivaldi's part. There are fixed it in the last snapshot.
